version: "3.8"

services:
  facultades-service:
    build: .
    container_name: facultades_container
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
