version: '3.8'

services:
  investigadores-service:
    build: .
    container_name: investigadores-service
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://host.docker.internal:27017/universidad
    networks:
      - red-microservicios

networks:
  red-microservicios:
